/**
 * Pure response builders for the browser dev preview (see `dev-mock-api.ts`).
 *
 * Nothing here touches mock state: every function is a deterministic mapping
 * from (engine, table, request) to the shape the real Rust backend returns.
 */
import type {
  ColumnDiff,
  DbEngine,
  DatabaseDiff,
  DatabaseInfo,
  ExplainSQLResult,
  IndexDiff,
  QueryRowsRequest,
  QueryRowsResult,
  SqlDbEngine,
  SyncPlan,
  TableDataDiff,
  TableDiff,
  TableRowComparison,
  TableSchema
} from '../../shared/types'
import {
  column,
  hex,
  isoAt,
  pick,
  REDIS_COLUMNS,
  tableDef,
  type MockTableDef
} from './dev-mock-fixtures'
import {
  createNoPrimaryKeyQueryRowsResult,
  createQueryRowsResult
} from '../components/table-view/table-data-test-helpers'

function redisRows(key: string, page: number, pageSize: number): QueryRowsResult {
  const total = key.startsWith('cache:') ? 6 : key.startsWith('queue') ? 24 : 1
  const start = (page - 1) * pageSize
  const rows: Record<string, unknown>[] = []
  for (let i = start; i < Math.min(total, start + pageSize); i += 1) {
    rows.push(
      total === 1
        ? { field: key, value: `"${hex(i + key.length, 24)}"` }
        : { field: `${pick(['name', 'email', 'ttl', 'hits', 'region', 'plan'], i)}`, value: hex(i + key.length, 12) }
    )
  }
  return { rows, total, hasPrimaryKey: true, primaryKey: ['field'], columns: REDIS_COLUMNS }
}

function sqlRows(req: QueryRowsRequest): QueryRowsResult {
  const def = tableDef(req.table)
  const pageSize = Math.max(1, req.pageSize)
  const page = Math.max(1, req.page)

  // A WHERE fragment cannot be evaluated without a real engine; the mock
  // narrows the result set deterministically so pagination + the "filtered"
  // count still behave believably.
  const where = req.where?.trim()
  const total = where ? Math.max(1, def.rowCount % 97 || 13) : def.rowCount
  const offset = where ? (def.rowCount % 500) : 0

  const descending = req.orderBy?.dir === 'DESC'
  const start = (page - 1) * pageSize
  const rows: Record<string, unknown>[] = []
  for (let i = start; i < Math.min(total, start + pageSize); i += 1) {
    const index = descending ? total - 1 - i : i
    rows.push(def.makeRow(index + offset))
  }

  return {
    rows,
    total,
    hasPrimaryKey: def.primaryKey.length > 0,
    primaryKey: def.primaryKey,
    columns: def.columns
  }
}

export function queryRowsResult(engine: DbEngine, req: QueryRowsRequest): QueryRowsResult {
  if (engine === 'redis') return redisRows(req.table, req.page, req.pageSize)
  if (req.table === 'feature_flags') return createQueryRowsResult()
  if (req.table === 'v_feature_flags') return createNoPrimaryKeyQueryRowsResult()
  return sqlRows(req)
}

export function renderCreateSQL(engine: SqlDbEngine, table: string, def: MockTableDef): string {
  const quote = engine === 'postgres' ? '"' : '`'
  const q = (name: string) => `${quote}${name}${quote}`
  const lines = def.columns.map((c) => {
    const parts = [`  ${q(c.name)} ${c.type}`]
    if (!c.nullable) parts.push('NOT NULL')
    if (c.defaultValue !== null) parts.push(`DEFAULT '${c.defaultValue}'`)
    if (c.isAutoIncrement) parts.push(engine === 'postgres' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT')
    if (c.comment && engine === 'mysql') parts.push(`COMMENT '${c.comment}'`)
    return parts.join(' ')
  })
  if (def.primaryKey.length > 0) {
    lines.push(`  PRIMARY KEY (${def.primaryKey.map(q).join(', ')})`)
  }
  for (const index of def.indexes) {
    if (index.name === 'PRIMARY') continue
    lines.push(
      `  ${index.unique ? 'UNIQUE KEY' : 'KEY'} ${q(index.name)} (${index.columns.map(q).join(', ')})`
    )
  }
  const suffix =
    engine === 'postgres' ? ');' : ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;'
  return `CREATE TABLE ${q(table)} (\n${lines.join(',\n')}\n${suffix}`
}

export function tableSchema(engine: SqlDbEngine, table: string): TableSchema {
  const def = tableDef(table)
  const avgRowLength = 64 + def.columns.length * 24
  return {
    name: table,
    columns: def.columns,
    indexes: def.indexes,
    primaryKey: def.primaryKey,
    createSQL: renderCreateSQL(engine, table, def),
    rowEstimate: def.rowCount,
    engine: engine === 'postgres' ? 'heap' : 'InnoDB',
    charset: engine === 'postgres' ? 'UTF8' : 'utf8mb4',
    tableComment: def.comment,
    dataLength: def.rowCount * avgRowLength,
    indexLength: def.rowCount * 18 * Math.max(1, def.indexes.length),
    dataFree: 4096,
    avgRowLength,
    autoIncrement: def.primaryKey.length > 0 ? def.rowCount + 1 : null,
    createdAt: isoAt(320),
    updatedAt: isoAt(1)
  }
}

export function databaseInfo(args: {
  engine: DbEngine
  database: string
  tables: string[]
  /** Redis reports a key count that can exceed the listed keys. */
  redisKeyCount?: number
}): DatabaseInfo {
  const { engine, database, tables } = args
  if (engine === 'redis') {
    const total = args.redisKeyCount ?? tables.length
    return { name: database, tableCount: total, rowEstimate: total }
  }
  const sqlEngine: SqlDbEngine = engine === 'postgres' ? 'postgres' : 'mysql'
  let rowEstimate = 0
  let dataLength = 0
  let indexLength = 0
  for (const table of tables) {
    const schema = tableSchema(sqlEngine, table)
    rowEstimate += schema.rowEstimate ?? 0
    dataLength += schema.dataLength ?? 0
    indexLength += schema.indexLength ?? 0
  }
  return {
    name: database,
    tableCount: tables.length,
    rowEstimate,
    dataLength,
    indexLength,
    totalSize: dataLength + indexLength,
    dataFree: 65_536,
    charset: sqlEngine === 'postgres' ? 'UTF8' : 'utf8mb4',
    collation: sqlEngine === 'postgres' ? 'en_US.UTF-8' : 'utf8mb4_0900_ai_ci',
    owner: sqlEngine === 'postgres' ? 'postgres' : undefined,
    comment: ''
  }
}

function modifiedColumnDiffs(table: string): ColumnDiff[] {
  const def = tableDef(table)
  const first = def.columns[1]
  const last = def.columns[def.columns.length - 1]
  const diffs: ColumnDiff[] = []
  if (first) {
    diffs.push({
      name: first.name,
      kind: 'modified',
      source: first,
      target: { ...first, type: first.type.replace(/\d+/, (n) => String(Number(n) * 2)), nullable: true }
    })
  }
  if (last && last !== first) {
    diffs.push({ name: last.name, kind: 'only-in-source', source: last })
  }
  diffs.push({
    name: 'legacy_flag',
    kind: 'only-in-target',
    target: column('legacy_flag', 'tinyint(1)', { nullable: true, defaultValue: '0' })
  })
  return diffs
}

function modifiedIndexDiffs(table: string): IndexDiff[] {
  const def = tableDef(table)
  const secondary = def.indexes.find((i) => i.name !== 'PRIMARY')
  if (!secondary) return []
  return [
    {
      name: secondary.name,
      kind: 'modified',
      source: secondary,
      target: { ...secondary, unique: !secondary.unique }
    }
  ]
}

export function dataDiffFor(table: string): TableDataDiff {
  const def = tableDef(table)
  if (def.primaryKey.length === 0) {
    return {
      comparable: false,
      reason: 'No primary key on either side; rows cannot be matched.',
      keyColumns: [],
      compareColumns: [],
      sourceRowCount: def.rowCount,
      targetRowCount: def.rowCount,
      sourceOnly: 0,
      targetOnly: 0,
      modified: 0,
      identical: 0,
      samples: []
    }
  }
  // The three buckets must add up to at most `rowCount`, or a small table
  // reports a negative "identical" count in the comparison status panel —
  // `feature_flags` has 3 rows and the unclamped seeds claim 5 + 6 of them.
  const rowCount = def.rowCount
  const sourceOnly = Math.min((rowCount % 7) + 2, Math.floor(rowCount / 3))
  const modified = Math.min((rowCount % 11) + 3, rowCount - sourceOnly - Math.floor(rowCount / 3))
  const targetOnly = Math.min((rowCount % 5) + 1, Math.max(1, Math.ceil(rowCount / 6)))
  const samples = [
    ...Array.from({ length: Math.min(3, sourceOnly) }, (_, i) => ({
      kind: 'only-in-source' as const,
      key: String(i + 1),
      source: def.makeRow(i)
    })),
    ...Array.from({ length: Math.min(2, targetOnly) }, (_, i) => ({
      kind: 'only-in-target' as const,
      key: String(900 + i),
      target: def.makeRow(900 + i)
    })),
    ...Array.from({ length: Math.min(3, modified) }, (_, i) => {
      const source = def.makeRow(100 + i)
      const target = { ...source }
      const changed = def.columns[1]?.name
      if (changed) target[changed] = `${String(source[changed])}·staging`
      return { kind: 'modified' as const, key: String(101 + i), source, target }
    })
  ]
  return {
    comparable: true,
    keyColumns: def.primaryKey,
    compareColumns: def.columns.map((c) => c.name),
    sourceRowCount: rowCount,
    targetRowCount: rowCount - sourceOnly + targetOnly,
    sourceOnly,
    targetOnly,
    modified,
    identical: rowCount - sourceOnly - modified,
    samples
  }
}

const MODIFIED_TABLES = new Set(['users', 'orders'])

export function tableDiffFor(table: string, kind: TableDiff['kind'], includeData: boolean): TableDiff {
  return {
    table,
    kind,
    columnDiffs: kind === 'modified' ? modifiedColumnDiffs(table) : [],
    indexDiffs: kind === 'modified' ? modifiedIndexDiffs(table) : [],
    dataDiff: includeData ? dataDiffFor(table) : undefined
  }
}

export function buildDatabaseDiff(args: {
  sourceDatabase: string
  sourceTables: string[]
  targetDatabase: string
  targetTables: string[]
  includeData: boolean
  only?: string[]
}): DatabaseDiff {
  const { sourceDatabase, targetDatabase, includeData, only } = args
  const filter = only && only.length > 0 ? new Set(only) : null
  const sourceTables = args.sourceTables.filter((t) => !filter || filter.has(t))
  const targetTables = args.targetTables.filter((t) => !filter || filter.has(t))
  const targetSet = new Set(targetTables)

  const tableDiffs: TableDiff[] = []
  const rowComparisons: TableRowComparison[] = []

  for (const table of sourceTables) {
    if (!targetSet.has(table)) {
      tableDiffs.push(tableDiffFor(table, 'only-in-source', includeData))
      continue
    }
    if (MODIFIED_TABLES.has(table)) {
      tableDiffs.push(tableDiffFor(table, 'modified', includeData))
    }
    if (includeData) {
      rowComparisons.push({ table, dataDiff: dataDiffFor(table) })
    }
  }
  const sourceSet = new Set(sourceTables)
  for (const table of targetTables) {
    if (!sourceSet.has(table)) tableDiffs.push(tableDiffFor(table, 'only-in-target', includeData))
  }

  return { sourceDatabase, targetDatabase, tableDiffs, rowComparisons }
}

// -- sync ----------------------------------------------------------------

export function buildSyncPlan(tables: string[], syncStructure: boolean, syncData: boolean): SyncPlan {
  return {
    steps: tables.map((table) => {
      const def = tableDef(table)
      const sqls: string[] = []
      if (syncStructure) {
        sqls.push(`DROP TABLE IF EXISTS \`${table}\`;`)
        sqls.push(renderCreateSQL('mysql', table, def))
      }
      if (syncData) {
        const columns = def.columns.map((c) => `\`${c.name}\``).join(', ')
        sqls.push(`INSERT INTO \`${table}\` (${columns}) VALUES /* ${def.rowCount} rows */ ...;`)
      }
      return {
        table,
        description:
          syncStructure && syncData
            ? `Recreate ${table} and copy ${def.rowCount} rows`
            : syncStructure
              ? `Recreate ${table}`
              : `Copy ${def.rowCount} rows into ${table}`,
        sqls
      }
    })
  }
}


export function terminalPrompt(): string {
  return '\u001b[1;34mdeploy@bastion\u001b[0m:\u001b[1;36m~\u001b[0m$ '
}

export function terminalBanner(connectionName: string): string {
  return [
    '\u001b[2mLast login: Mon Jul 27 09:00:00 2026 from 10.0.0.9\u001b[0m',
    `Welcome to ${connectionName} (mock session — \`npm run dev:ui\` has no SSH backend)`,
    'Try: ls, pwd, whoami, uname -a',
    ''
  ].join('\r\n')
}

export function terminalCommandOutput(command: string): string {
  switch (command) {
    case '':
      return ''
    case 'ls':
      return 'app  current  deploy.sh  notes.md  releases  shop-2026-07-26.sql.gz'
    case 'pwd':
      return '/home/deploy'
    case 'whoami':
      return 'deploy'
    case 'uname -a':
      return 'Linux bastion 6.8.0-45-generic #45-Ubuntu SMP x86_64 GNU/Linux'
    default:
      return `${command.split(' ')[0] ?? command}: command not found`
  }
}


export function executeStatements(sql: string): unknown {
  const statements = sql
    .split(';')
    .map((part) => part.trim())
    .filter((part) => part.length > 0)

  if (statements.length === 0) return []

  const run = (statement: string): unknown => {
    const head = statement.slice(0, 12).toLowerCase()
    if (head.startsWith('select') || head.startsWith('show') || head.startsWith('with') || head.startsWith('describe') || head.startsWith('desc ')) {
      const table = /\bfrom\s+[`"']?([a-z_][a-z0-9_]*)/i.exec(statement)?.[1] ?? 'users'
      const def = tableDef(table)
      const limit = Number(/\blimit\s+(\d+)/i.exec(statement)?.[1] ?? 25)
      return Array.from({ length: Math.min(limit, 100, def.rowCount) }, (_, i) => def.makeRow(i))
    }
    return { affectedRows: (statement.length % 9) + 1, insertId: 0, warningStatus: 0 }
  }

  if (statements.length === 1) {
    const only = statements[0]
    return only === undefined ? [] : run(only)
  }
  return statements.map((statement) => {
    const result = run(statement)
    return Array.isArray(result) ? { affectedRows: result.length, insertId: 0 } : result
  })
}

export function explainResult(engine: SqlDbEngine, sql: string): ExplainSQLResult {
  const table = /\bfrom\s+[`"']?([a-z_][a-z0-9_]*)/i.exec(sql)?.[1] ?? 'users'
  const def = tableDef(table)
  const rows = def.primaryKey.length > 0 ? Math.ceil(def.rowCount / 4) : def.rowCount
  return {
    engine,
    statement: sql,
    summary: [
      { label: 'Estimated rows', value: rows },
      { label: 'Estimated cost', value: (rows * 1.12).toFixed(2) },
      { label: 'Access type', value: def.primaryKey.length > 0 ? 'range' : 'ALL' }
    ],
    plan: {
      id: 'node-0',
      label: engine === 'postgres' ? 'Seq Scan' : 'SIMPLE',
      detail: table,
      metrics: [
        { label: 'rows', value: rows },
        { label: 'filtered', value: '62.50%' }
      ],
      children:
        def.indexes.length > 1
          ? [
              {
                id: 'node-1',
                label: engine === 'postgres' ? 'Index Scan' : 'ref',
                detail: def.indexes[1]?.name ?? 'PRIMARY',
                metrics: [{ label: 'rows', value: Math.ceil(rows / 8) }],
                children: []
              }
            ]
          : []
    },
    columns: ['id', 'select_type', 'table', 'type', 'rows', 'Extra'],
    rows: [
      {
        id: 1,
        select_type: 'SIMPLE',
        table,
        type: def.primaryKey.length > 0 ? 'range' : 'ALL',
        rows,
        Extra: 'Using where'
      }
    ]
  }
}
