import type { ColumnInfo, DbEngine, IndexInfo, TableSchema } from '../../../shared/types'
import type { Dialect } from './types'

function escapeIdent(name: string): string {
  return name.replace(/"/g, '""')
}

export const pgDialect: Dialect = {
  engine: 'postgres',

  quoteIdent(name) {
    return `"${escapeIdent(name)}"`
  },

  quoteTable(database, table) {
    // PG：MVP 把 UI 层传入的 database 视为 schema（下层 pg Client 已绑定具体 database）。
    return `${this.quoteIdent(database)}.${this.quoteIdent(table)}`
  },

  formatLiteral(value) {
    if (value === null || value === undefined) return 'NULL'
    if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL'
    if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE'
    if (value instanceof Date) return `'${value.toISOString()}'`
    if (Buffer.isBuffer(value)) return `'\\x${value.toString('hex')}'`
    if (typeof value === 'object') {
      const s = JSON.stringify(value).replace(/'/g, "''")
      return `'${s}'`
    }
    const s = String(value).replace(/'/g, "''")
    return `'${s}'`
  },

  renderInsert(database, table, columns, rows) {
    const target = this.quoteTable(database, table)
    const columnList = columns.map((c) => this.quoteIdent(c.name)).join(', ')
    const valuesSQL = rows
      .map((row) => {
        const vals = columns.map((c) => this.formatLiteral(row[c.name]))
        return `(${vals.join(', ')})`
      })
      .join(',\n  ')
    return `INSERT INTO ${target} (${columnList}) VALUES\n  ${valuesSQL};`
  },

  renderTruncate(database, table) {
    return `TRUNCATE TABLE ${this.quoteTable(database, table)} RESTART IDENTITY;`
  },

  renderDropIfExists(database, table) {
    return `DROP TABLE IF EXISTS ${this.quoteTable(database, table)};`
  },

  /** PG 不需要 DEFINER 清理 */
  stripDefiner(sql) {
    return sql
  }
}

interface RenderPgCreateTableOptions {
  includeSchema?: boolean
  sourceEngine?: DbEngine
}

/** 从 schema 重建 CREATE TABLE（MVP：列 / NOT NULL / DEFAULT / PRIMARY KEY / UNIQUE / 普通索引） */
export function renderPgCreateTable(
  schema: TableSchema,
  database: string,
  options: RenderPgCreateTableOptions = {}
): string {
  const q = pgDialect.quoteIdent.bind(pgDialect)
  const target = pgDialect.quoteTable(database, schema.name)

  const columnDefs = schema.columns.map((c) => renderColumnDef(c, options.sourceEngine))
  const pkCols = schema.primaryKey
  if (pkCols.length > 0) {
    columnDefs.push(`PRIMARY KEY (${pkCols.map((n) => q(n)).join(', ')})`)
  }

  const lines = [`CREATE TABLE ${target} (`, columnDefs.map((l) => `  ${l}`).join(',\n'), ');']
  const body = lines.join('\n')

  const indexStmts = schema.indexes
    .filter((i) => i.name !== 'PRIMARY' && !isPkIndex(i, pkCols))
    .map((i) => renderIndex(database, schema.name, i))

  const comments: string[] = []
  if (schema.tableComment) {
    comments.push(
      `COMMENT ON TABLE ${target} IS ${pgDialect.formatLiteral(schema.tableComment)};`
    )
  }
  for (const c of schema.columns) {
    if (c.comment) {
      comments.push(
        `COMMENT ON COLUMN ${target}.${q(c.name)} IS ${pgDialect.formatLiteral(c.comment)};`
      )
    }
  }

  return [options.includeSchema ? `CREATE SCHEMA IF NOT EXISTS ${q(database)};` : '', body, ...indexStmts, ...comments]
    .filter(Boolean)
    .join('\n')
}

function renderColumnDef(c: ColumnInfo, sourceEngine?: DbEngine): string {
  const q = pgDialect.quoteIdent.bind(pgDialect)
  const type = sourceEngine === 'mysql' ? mapMySQLTypeToPg(c.type) : c.type
  const parts = [`${q(c.name)} ${type}`]
  const canUseIdentity = sourceEngine === 'mysql' && c.isAutoIncrement && isPgIntegerType(type)

  if (canUseIdentity) {
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  }
  if (!c.nullable) parts.push('NOT NULL')

  const defaultValue = renderDefaultValue(c, type, sourceEngine, canUseIdentity)
  if (defaultValue) {
    parts.push(`DEFAULT ${defaultValue}`)
  }
  return parts.join(' ')
}

function mapMySQLTypeToPg(type: string): string {
  const normalized = type.trim().toLowerCase()
  const unsigned = /\bunsigned\b/.test(normalized)
  const base = normalized.replace(/\bunsigned\b|\bzerofill\b/g, '').replace(/\s+/g, ' ').trim()

  if (/^tinyint\b/.test(base)) return 'smallint'
  if (/^smallint\b/.test(base)) return unsigned ? 'integer' : 'smallint'
  if (/^mediumint\b/.test(base)) return 'integer'
  if (/^(int|integer)\b/.test(base)) return unsigned ? 'bigint' : 'integer'
  if (/^bigint\b/.test(base)) return unsigned ? 'numeric(20)' : 'bigint'
  if (/^(decimal|numeric)\b/.test(base)) return base.replace(/^decimal/, 'numeric')
  if (/^float\b/.test(base)) return 'real'
  if (/^(double|real)\b/.test(base)) return 'double precision'
  if (/^bit\b/.test(base)) return base
  if (/^bool(ean)?\b/.test(base)) return 'boolean'
  if (/^char\b/.test(base)) return base
  if (/^varchar\b/.test(base)) return base
  if (/^(tinytext|mediumtext|longtext|text|enum|set)\b/.test(base)) return 'text'
  if (/^(binary|varbinary|tinyblob|mediumblob|longblob|blob)\b/.test(base)) return 'bytea'
  if (/^datetime\b/.test(base)) return 'timestamp'
  if (/^timestamp\b/.test(base)) return 'timestamp'
  if (/^date\b/.test(base)) return 'date'
  if (/^time\b/.test(base)) return 'time'
  if (/^year\b/.test(base)) return 'integer'
  if (/^json\b/.test(base)) return 'jsonb'
  return 'text'
}

function renderDefaultValue(
  column: ColumnInfo,
  pgType: string,
  sourceEngine: DbEngine | undefined,
  skipForIdentity: boolean
): string | null {
  if (skipForIdentity) return null
  if (column.defaultValue === null || column.defaultValue === undefined) return null

  const raw = String(column.defaultValue).trim()
  if (!raw) return null
  if (/^null$/i.test(raw)) return 'NULL'
  if (/^current_(timestamp|date|time)(\(\))?$/i.test(raw)) {
    return raw.replace(/\(\)$/, '').toUpperCase()
  }

  if (sourceEngine !== 'mysql') return raw
  if (/^b'[01]+'$/i.test(raw)) return raw.slice(2, -1)
  if (/^-?\d+(\.\d+)?$/.test(raw)) return raw
  if (/^'.*'$/.test(raw)) return raw
  if (isPgStringType(pgType)) return pgDialect.formatLiteral(raw)
  return raw
}

function isPgIntegerType(type: string): boolean {
  return /^(smallint|integer|bigint)$/.test(type)
}

function isPgStringType(type: string): boolean {
  return /^(text|char\b|varchar\b|jsonb\b|date\b|time\b|timestamp\b)/.test(type)
}

function renderIndex(database: string, table: string, index: IndexInfo): string {
  const q = pgDialect.quoteIdent.bind(pgDialect)
  const unique = index.unique ? 'UNIQUE ' : ''
  const cols = index.columns.map((c) => q(c)).join(', ')
  return `CREATE ${unique}INDEX ${q(index.name)} ON ${pgDialect.quoteTable(database, table)} (${cols});`
}

function isPkIndex(index: IndexInfo, pkCols: string[]): boolean {
  if (!index.unique) return false
  if (index.columns.length !== pkCols.length) return false
  return index.columns.every((c, i) => c === pkCols[i])
}
